apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
    - productpage
  http:
  - match:
    - headers:
        User-Agent:
          regex: ^.*Mobile.*$
    route:
    - headers:
        request:
          set:
            Cookie: "session=eyJ1c2VyIjoibmFydXRvIn0.X4LLaw.KFK-tAcva5PnDrWHEN01KdlBAVE"
      destination:
        host: productpage
        subset: v1
  - route:
    - destination:
        host: product
        subset: v2
