apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - headers:
        User-Agent:
          regex: ^.*Mobile.*$
    route:
    - headers:
        request:
          set:
            x-response: "Success with Mobile"
      destination:
        host: productpage
        port:
          number: 9080
  - route:
    - destination:
        host: product
        subset: random
